[flint]
version = 1
plugins_branch = "plugin-system-improvements"

[common]

[rules]

[tests.jest]
enabled = true
config_path = "src/jest.config.ts"
test_environment = "node"
verbose = true
collect_coverage = true
test_files_include = ["src/*.test.js"]
test_files_ignore = ["node_modules/", "dist/"]

[config]

[ci.github-actions]

[report.json]
output_path = "reports"
