[flint]
version = 1
plugins_branch = "ai"
env = ".env"

[rules.common]
# Basic style settings
max_line_length = 100
quote_style = "double"
require_semicolons = true
indent_style = "spaces"
indent_size = 4

# Naming conventions
variable_case = "camelCase"
function_case = "camelCase"
class_case = "PascalCase"
constant_case = "UPPER_CASE"

# Whitespace rules
no_trailing_spaces = true
no_multiple_empty_lines = true
space_before_blocks = true

# Operator and syntax styling (cross-language)
indent_binary_ops = true
operator_linebreak = "before"


# [rules.eslint]

[config.eslint]
exclude = ["*.config.js", "coverage/**/*", "node_modules/**/*"]
include = ["src/**/*.js"]

[tests.jest]
enabled = true
config_path = "src/jest.config.ts"
test_environment = "node"
verbose = true
collect_coverage = true
include = ["src/*.test.js"]
exclude = ["node_modules/", "dist/"]


[ci.github-actions]
artifacts = "reports"

# [report.db]
# host = "env:MYSQL_HOST"
# port = "env:MYSQL_PORT"
# username = "env:MYSQL_USERNAME"
# password = "env:MYSQL_PASSWORD"
# database = "env:MYSQL_DATABASE"

[report.json]
output_path = "reports"

# [report.md]
# output_path = "reports"

# [report.ai]
# api_key = "env:GEMINI_API_KEY"
# api_base_url = "env:GEMINI_BASE_URL"
# model = "gemini-2.0-flash"
