[flint]
version = 1
plugins_branch = "plugin-system-improvements"

[common.indent]
indent_style = "spaces"
indent_size = 4
switch_case = 5
function_declaration = { body = 2, parameters = 3 }

[common]
# Basic style settings
max_line_length = 100
quote_style = "double"
require_semicolons = true

# Naming conventions
variable_case = "camelCase"
function_case = "camelCase"
class_case = "PascalCase"
constant_case = "UPPER_CASE"

# Whitespace rules
no_trailing_spaces = true
no_multiple_empty_lines = true
space_before_blocks = true

# Operator and syntax styling (cross-language)
indent_binary_ops = true
operator_linebreak = "before"


[rules.eslint]
arrow-parens = "always"
arrow-spacing = "consistent"
jsx-quotes = "prefer-double"
object-curly-spacing = "always"
array-bracket-spacing = "never"
space-before-function-paren = "never"
wrap-iife = "inside"

[config.eslint]
exclude = ["node_modules", "coverage"]
include = ["src/*"]

[tests.jest]
enabled = true
config_path = "src/jest.config.ts"
test_environment = "node"
verbose = true
collect_coverage = true
test_files_include = ["src/*.test.js"]
test_files_ignore = ["node_modules/", "dist/"]


[ci.github-actions]

[report.json]
output_path = "reports"
