on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
name: Flint CI
jobs:
  flint_checks:
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      name: Install Node.js
      with:
        node-version: 18.x
    - name: Install Node.js dependencies
      run: npm install -g jest@latest --no-fund --no-audit --silent
    - uses: robinraju/release-downloader@v1
      name: Install Flint
      with:
        latest: true
        repository: skadewdl3/flint
        fileName: flint
        out-file-path: .
        prerelease: true
    - env:
        API_KEY: env:GEMINI_API_KEY
        API_BASE_URL: env:GEMINI_BASE_URL
        MODEL: gemini-2.0-flash
      name: Run Tests
      run: "        chmod +x ./flint\n        ./flint install\n        ./flint test --test\n        "
    - uses: actions/upload-artifact@v4
      name: Upload Test Results
      with:
        name: Test Results
        path: reports
    - uses: actions/upload-artifact@v4
      name: Upload Logs
      with:
        name: Logs
        path: logs.txt
    name: Flint Checks
    runs-on: ubuntu-latest
