on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
name: Flint CI
jobs:
  flint_checks:
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      name: Install Node.js
      with:
        node-version: 18.x
    - name: Install Node.js dependencies
      run: npm install -g @stylisic/eslint-config@latest @stylisic/eslint-plugin@latest @stylisic/eslint-plugin-js@latest @stylisic/eslint-plugin-jsx@latest eslint@latest jest@latest --no-fund --no-audit --silent
    - uses: robinraju/release-downloader@v1
      name: Install Flint
      with:
        latest: true
        repository: skadewdl3/flint
        fileName: flint
        out-file-path: .
        prerelease: true
    - env:
        GEMINI_BASE_URL: ${{ secrets.GEMINI_BASE_URL }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        MODEL: deepseek-coder
      name: Run Tests
      run: "        chmod +x ./flint\n        ./flint install\n        ./flint test --test\n        "
    - env:
        GH_TOKEN: '${{ secrets.GH_TOKEN }} '
      name: Comment AI Suggestions
      run: "        if [ -f temp.md ]; then\n        gh pr comment ${{ github.event.pull_request.number }} --body \"$(cat temp.md)\"\n        else\n        echo \"AI suggestions not found, skipping PR comment.\"\n        fi\n        "
    - uses: actions/upload-artifact@v4
      name: Upload Test Results
      with:
        name: Test Results
        path: reports
    - uses: actions/upload-artifact@v4
      name: Upload Logs
      with:
        name: Logs
        path: logs.txt
    name: Flint Checks
    runs-on: ubuntu-latest
