on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
name: Flint CI
jobs:
  flint_checks:
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: "                            sudo apt-get update\n                            sudo apt-get install -y git curl build-essential\n                            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh\n                            source \"$HOME/.cargo/env\"\n                        "
    - name: Install Flint
      run: "                            git clone https://github.com/skadewdl3/flint\n                            cd flint\n                            cargo build --release\n                            cp target/release/flint ../flint\n                            echo \"$PWD\" >> $GITHUB_PATH\n                            cd ..\n                            chmod +x ./flint\n                        "
    - name: Run Tests
      run: "                            ./flint test --test\n                            echo \"Processing test results...\"\n                        "
    - uses: actions/upload-artifact@v4
      name: Upload Test Results
      with:
        name: .flint/reports/reports/report.json
        path: .flint/reports/reports/report.json
    name: Flint Checks
    runs-on: ubuntu-latest
