on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
name: Flint CI
jobs:
  flint_checks:
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      name: Install Node.js
      with:
        node-version: 18.x
    - name: Install Jest and ESLint
      run: "                                npm install -g jest eslint --no-fund --no-audit --silent\n                                echo \"Node.js, Jest, and ESLint installed successfully\"\n                                "
    - name: Install Flint
      run: "                            git clone https://github.com/skadewdl3/flint\n                            cd flint\n                            cargo build --release\n                            cp target/release/flint ../flint\n                            echo \"$PWD\" >> $GITHUB_PATH\n                            cd ..\n                            chmod +x ./flint\n                        "
    - name: Run Tests
      run: "                            ./flint test --test\n                            echo \"Processing test results...\"\n                        "
    - uses: actions/upload-artifact@v3
      name: Upload Test Results
      with:
        name: .flint/reports/reports/report.json
        path: .flint/reports/reports/report.json
    - uses: actions/upload-artifact@v3
      name: Upload Logs
      with:
        name: logs
        path: logs.txt
    name: Flint Checks
    runs-on: ubuntu-latest
